workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    CirclemindSDK-OAS:
        inputs:
            - location: ./sdk/openapi.json
        registry:
            location: registry.speakeasyapi.dev/circlemind/circlemind/circlemind-sdk-oas
targets:
    circlemind-sdk:
        target: python
        source: CirclemindSDK-OAS
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/circlemind/circlemind/circlemind-sdk-oas-python-code-samples
            blocking: false
